name: Build Flatpak CI 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: "Check version"
        run: cat /etc/os-release
      
      - name: "Code Checkout"
        uses: actions/checkout@v4
        
      - name: "Install BuildStream2"
        run: |
          sudo dnf install -y bubblewrap fuse3 git lzip patch python3 git python3-pip fuse3 fuse3-devel
          pip install buildstream buildstream-plugins buildstream-external bst-plugins-experimental dulwich         

      - name: "Clone repo"
        run: git clone https://github.com/WinsDominoes/rocm-flatpak
        
      - name: "Build .bst file"
        run: bst build rocm-flatpak.bst

      - name: "Bst Artifact"
        run: bst artifact checkout --directory ./rocm-repo rocm-flatpak.bst
          
      - name: "Add Flatpak Remote"
        run: flatpak remote-add --user rocm-repo ./rocm-repo --no-gpg-verify
      
      - name: "Install Flatpak"
        run: flatpak install --user org.freedesktop.Platform.GL.ROCm

      - name: "Build Flatpak"
        run: flatpak build-bundle --runtime ./rocm-repo rocm.flatpak org.freedesktop.Platform.GL.ROCm 23.08

      - name: "Release to Github"
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rocm.flatpak"
          tag: "latest"
          commit: ${{ github.sha }}
          allowUpdates: true 
